version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: www-data
    group: www-data
hooks:
  ApplicationStop:
    - location: deploy/stopservice.sh
      timeout: 10
      runas: ubuntu
  AfterInstall:
    - location: deploy/afterinstall.sh
      timeout: 1200
      runas: ubuntu
  ApplicationStart:
    - location: deploy/startservice.sh
      timeout: 60
      runas: ubuntu